# Desgined to follow egl.h in the OpenEGL standard
# version 1.5. We followed a similar flow than 
# pysdl2

from ctypes import Structure, POINTER, c_int, c_void_p, c_char_p, c_float, \
    py_object, CFUNCTYPE
from .dll import _bind, nullfunc

__all__ = [EGL_CONTEXT_MAJOR_VERSION,
EGL_CONTEXT_MINOR_VERSION,
EGL_CONTEXT_OPENGL_PROFILE_MASK,
EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY = 0x31BD
EGL_NO_RESET_NOTIFICATION = 0x31BE
EGL_LOSE_CONTEXT_ON_RESET = 0x31BF
EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT = 0x00000001
EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT = 0x00000002
EGL_CONTEXT_OPENGL_DEBUG  = 0x31B0
EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE = 0x31B1
EGL_CONTEXT_OPENGL_ROBUST_ACCESS = 0x31B2
EGL_OPENGL_ES3_BIT = 0x00000040
EGL_CL_EVENT_HANDLE = 0x309C
EGL_SYNC_CL_EVENT  = 0x30FE
EGL_SYNC_CL_EVENT_COMPLETE  = 0x30FF
EGL_SYNC_PRIOR_COMMANDS_COMPLETE =  0x30F0
EGL_SYNC_TYPE                    = 0x30F7
EGL_SYNC_STATUS                  = 0x30F1
EGL_SYNC_CONDITION               = 0x30F8
EGL_SIGNALED                     = 0x30F2
EGL_UNSIGNALED                   = 0x30F3
EGL_SYNC_FLUSH_COMMANDS_BIT      = 0x0001
EGL_FOREVER                      = 0xFFFFFFFFFFFFFFFF #ull
EGL_TIMEOUT_EXPIRED              = 0x30F5
EGL_CONDITION_SATISFIED          = 0x30F6
EGL_NO_SYNC                      = c_void_p # original ((EGLSync)0)
EGL_SYNC_FENCE                   = 0x30F9
EGL_GL_COLORSPACE                = 0x309D
EGL_GL_COLORSPACE_SRGB           = 0x3089
EGL_GL_COLORSPACE_LINEAR         = 0x308A
EGL_GL_RENDERBUFFER              = 0x30B9
EGL_GL_TEXTURE_2D                = 0x30B1
EGL_GL_TEXTURE_LEVEL             = 0x30BC
EGL_GL_TEXTURE_3D                = 0x30B2
EGL_GL_TEXTURE_ZOFFSET           = 0x30BD
EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X = 0x30B3
EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X = 0x30B4
EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y = 0x30B5
EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = 0x30B6
EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z = 0x30B7
EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = 0x30B8
EGL_IMAGE_PRESERVED                = 0x30D2
EGL_NO_IMAGE                      = c_void_p # original ((EGLImage)0)

]

EGL_CONTEXT_MAJOR_VERSION =  0x3098
EGL_CONTEXT_MINOR_VERSION =  0x30FB
EGL_CONTEXT_OPENGL_PROFILE_MASK = 0x30FD
EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY = 0x31BD
EGL_NO_RESET_NOTIFICATION = 0x31BE
EGL_LOSE_CONTEXT_ON_RESET = 0x31BF
EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT = 0x00000001
EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT = 0x00000002
EGL_CONTEXT_OPENGL_DEBUG  = 0x31B0
EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE = 0x31B1
EGL_CONTEXT_OPENGL_ROBUST_ACCESS = 0x31B2
EGL_OPENGL_ES3_BIT = 0x00000040
EGL_CL_EVENT_HANDLE = 0x309C
EGL_SYNC_CL_EVENT  = 0x30FE
EGL_SYNC_CL_EVENT_COMPLETE  = 0x30FF
EGL_SYNC_PRIOR_COMMANDS_COMPLETE =  0x30F0
EGL_SYNC_TYPE                    = 0x30F7
EGL_SYNC_STATUS                  = 0x30F1
EGL_SYNC_CONDITION               = 0x30F8
EGL_SIGNALED                     = 0x30F2
EGL_UNSIGNALED                   = 0x30F3
EGL_SYNC_FLUSH_COMMANDS_BIT      = 0x0001
EGL_FOREVER                      = 0xFFFFFFFFFFFFFFFF #ull
EGL_TIMEOUT_EXPIRED              = 0x30F5
EGL_CONDITION_SATISFIED          = 0x30F6
EGL_NO_SYNC                      = c_void_p # original ((EGLSync)0)
EGL_SYNC_FENCE                   = 0x30F9
EGL_GL_COLORSPACE                = 0x309D
EGL_GL_COLORSPACE_SRGB           = 0x3089
EGL_GL_COLORSPACE_LINEAR         = 0x308A
EGL_GL_RENDERBUFFER              = 0x30B9
EGL_GL_TEXTURE_2D                = 0x30B1
EGL_GL_TEXTURE_LEVEL             = 0x30BC
EGL_GL_TEXTURE_3D                = 0x30B2
EGL_GL_TEXTURE_ZOFFSET           = 0x30BD
EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X = 0x30B3
EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X = 0x30B4
EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y = 0x30B5
EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = 0x30B6
EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z = 0x30B7
EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = 0x30B8
EGL_IMAGE_PRESERVED                = 0x30D2
EGL_NO_IMAGE                      = c_void_p # original ((EGLImage)0)
